#!/usr/bin/env python3
"""Inject (and remove) the ClubLog developer API key in the app source.

Club Log issues an API key per *application*, not per operator, and the one it
guards - cty.xml, the country file every DXCC lookup needs - is the same for
everybody. So the key belongs in the shipped binary rather than in each user's
Settings. But Club Log's API Keys article is explicit that keys found published
on the web or in a Git repository are deleted without notice, and both of this
project's repos are public. Obfuscating the key past their scanners would be
the wrong answer to that.

So the key is injected at *build time* and never committed. The tracked form of
DXClusterAggregator/Utils/BuiltInCredentials.swift carries an EMPTY key, which
compiles and runs fine - the app just falls back to whatever the user typed in
Settings, exactly as it did before any of this existed.

    ./scripts/embed_clublog_key.py                # inject, key read from the
                                                  # installed app's prefs
    ./scripts/embed_clublog_key.py <40-hex-key>   # inject an explicit key
    ./scripts/embed_clublog_key.py --clear        # restore the empty form

`notarize.sh` does the inject/clear pair around the release build, so a normal
release needs none of this by hand. Check `git diff` is clean before committing
if you have run an inject yourself.

The XOR pad is not a security measure - the plaintext would be recoverable from
the binary either way. It is there so a shipped `.app` does not hand the key to
`strings` for free.
"""

import json
import plistlib
import subprocess
import sys
from pathlib import Path

PREFS = Path.home() / "Library/Preferences/com.vu2cpl.dxclusteraggregator.plist"
OUT = Path(__file__).resolve().parent.parent / "DXClusterAggregator/Utils/BuiltInCredentials.swift"
PAD = b"VU2CPL-DXCA-cty-obfuscation-pad!"

HEADER = '''import Foundation

/// The ClubLog developer API key the app ships with, or an empty string in a
/// source checkout.
///
/// The key unlocks `cdn.clublog.org/cty.php`, which serves `cty.xml` - the
/// country/prefix file behind every DXCC lookup here. Club Log issues it per
/// *application*, not per operator: it identifies DXClusterAggregator, and its
/// value is the same for every user. Asking each user to request one by hand
/// and wait for it was a first-run hard stop that bought nothing.
///
/// **This file is generated by `scripts/embed_clublog_key.py`. Do not
/// hand-edit, and do not commit a version of it with a real key in it.** The
/// tracked form holds an empty key; `notarize.sh` injects the real one for the
/// duration of a release build and clears it again afterwards. Club Log delete
/// keys they find published in a Git repository, and both vu2cpl repos that
/// touch this key are public - so the key ships in the binary and lives
/// nowhere in history.
///
/// With no key injected, `clubLogAPIKey` is empty and
/// `ClubLogConfig.effectiveAPIKey` falls back to whatever the operator typed
/// into Settings - the pre-2026-09 behaviour, so a source build is fully
/// functional.
///
/// Per-operator secrets (ClubLog callsign / email / app password, the Telegram
/// bot token) are deliberately never injected here: those authenticate a
/// person, not the app.
///
/// The XOR pad below is not encryption and is not pretending to be - anyone
/// with the binary can recover the bytes. It exists so a shipped `.app` does
/// not hand the key to `strings` for free.
enum BuiltInCredentials {
'''

FOOTER = '''
    /// The built-in ClubLog developer API key; empty in a source checkout.
    static let clubLogAPIKey: String = {
        let bytes = obfuscatedClubLogAPIKey.enumerated().map { index, byte in
            byte ^ pad[index % pad.count]
        }
        return String(decoding: bytes, as: UTF8.self)
    }()
}
'''


def key_from_prefs() -> str:
    """Read the API key out of the installed app's preferences.

    `defaults read` is preferred over reading the plist directly because
    cfprefsd may still be holding recent writes in memory.
    """
    try:
        raw = subprocess.run(
            ["defaults", "read", "com.vu2cpl.dxclusteraggregator", "clubLogConfig"],
            capture_output=True, text=True, check=True,
        ).stdout
        return json.loads(raw.strip().strip('"').replace('\\"', '"')).get("apiKey", "")
    except (subprocess.CalledProcessError, json.JSONDecodeError, FileNotFoundError):
        pass
    if PREFS.exists():
        with PREFS.open("rb") as fh:
            return json.loads(plistlib.load(fh)["clubLogConfig"]).get("apiKey", "")
    return ""


def byte_rows(data: bytes) -> str:
    if not data:
        return ""
    return "\n".join(
        "        " + ", ".join(f"0x{b:02x}" for b in data[i:i + 10]) + ","
        for i in range(0, len(data), 10)
    ).rstrip(",")


def write(enc: bytes) -> None:
    OUT.write_text(
        HEADER
        + "\n    private static let obfuscatedClubLogAPIKey: [UInt8] = [\n"
        + byte_rows(enc)
        + "\n    ]\n"
        + "\n    private static let pad: [UInt8] = [\n"
        + byte_rows(PAD)
        + "\n    ]\n"
        + FOOTER
    )


def main() -> int:
    arg = sys.argv[1] if len(sys.argv) > 1 else ""

    if arg in ("--clear", "--empty"):
        write(b"")
        print(f"cleared {OUT.name} — tracked form restored (no key)")
        return 0

    key = (arg or key_from_prefs()).strip()
    if len(key) != 40 or not all(c in "0123456789abcdefABCDEF" for c in key):
        print(
            "error: expected a 40-character hex ClubLog API key, "
            f"got {len(key)} character(s).\n"
            "Pass it as an argument, or set it in the app's "
            "Settings -> ClubLog -> API Key first.",
            file=sys.stderr,
        )
        return 1

    write(bytes(b ^ PAD[i % len(PAD)] for i, b in enumerate(key.encode("ascii"))))
    print(f"injected a key into {OUT.name} — clear it again before committing")
    return 0


if __name__ == "__main__":
    sys.exit(main())
