import Foundation

/// The ClubLog developer API key the app ships with, or an empty string in a
/// source checkout.
///
/// The key unlocks `cdn.clublog.org/cty.php`, which serves `cty.xml` - the
/// country/prefix file behind every DXCC lookup here. Club Log issues it per
/// *application*, not per operator: it identifies DXClusterAggregator, and its
/// value is the same for every user. Asking each user to request one by hand
/// and wait for it was a first-run hard stop that bought nothing.
///
/// **This file is generated by `scripts/embed_clublog_key.py`. Do not
/// hand-edit, and do not commit a version of it with a real key in it.** The
/// tracked form holds an empty key; `notarize.sh` injects the real one for the
/// duration of a release build and clears it again afterwards. Club Log delete
/// keys they find published in a Git repository, and both vu2cpl repos that
/// touch this key are public - so the key ships in the binary and lives
/// nowhere in history.
///
/// With no key injected, `clubLogAPIKey` is empty and
/// `ClubLogConfig.effectiveAPIKey` falls back to whatever the operator typed
/// into Settings - the pre-2026-09 behaviour, so a source build is fully
/// functional.
///
/// Per-operator secrets (ClubLog callsign / email / app password, the Telegram
/// bot token) are deliberately never injected here: those authenticate a
/// person, not the app.
///
/// The XOR pad below is not encryption and is not pretending to be - anyone
/// with the binary can recover the bytes. It exists so a shipped `.app` does
/// not hand the key to `strings` for free.
enum BuiltInCredentials {

    private static let obfuscatedClubLogAPIKey: [UInt8] = [

    ]

    private static let pad: [UInt8] = [
        0x56, 0x55, 0x32, 0x43, 0x50, 0x4c, 0x2d, 0x44, 0x58, 0x43,
        0x41, 0x2d, 0x63, 0x74, 0x79, 0x2d, 0x6f, 0x62, 0x66, 0x75,
        0x73, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x70, 0x61,
        0x64, 0x21
    ]

    /// The built-in ClubLog developer API key; empty in a source checkout.
    static let clubLogAPIKey: String = {
        let bytes = obfuscatedClubLogAPIKey.enumerated().map { index, byte in
            byte ^ pad[index % pad.count]
        }
        return String(decoding: bytes, as: UTF8.self)
    }()
}
